"""
.. module:: varnames
    :platform: Darwin, Linux, Unix, Windows
    :synopsis: Module that contains an enumeration of environment variable names
               that are used by the configuration code.

.. moduleauthor:: Myron Walker <myron.walker@gmail.com>
"""


import os


from mojo.config.overrides import MOJO_CONFIG_OVERRIDES


class MOJO_CONFIG_VARNAMES:

    MJR_CONFIG_DIRECTORY = "MJR_CONFIG_DIRECTORY"

    MJR_CONFIG_PASS_PHRASE = "MJR_CONFIG_PASS_PHRASE"

    MJR_CONFIG_CREDENTIAL_NAMES = "MJR_CONFIG_CREDENTIAL_NAMES"
    MJR_CONFIG_CREDENTIAL_URIS = "MJR_CONFIG_CREDENTIAL_URIS"
    MJR_CONFIG_CREDENTIAL_SOURCES = "MJR_CONFIG_CREDENTIAL_SOURCES"

    MJR_CONFIG_LANDSCAPE_NAMES = "MJR_CONFIG_LANDSCAPE_NAMES"
    MJR_CONFIG_LANDSCAPE_URIS = "MJR_CONFIG_LANDSCAPE_URIS"
    MJR_CONFIG_LANDSCAPE_SOURCES = "MJR_CONFIG_LANDSCAPE_SOURCES"

    MJR_CONFIG_TOPOLOGY_NAMES = "MJR_CONFIG_TOPOLOGY_NAMES"
    MJR_CONFIG_TOPOLOGY_URIS = "MJR_CONFIG_TOPOLOGY_URIS"
    MJR_CONFIG_TOPOLOGY_SOURCES = "MJR_CONFIG_TOPOLOGY_SOURCES"

    MJR_CONFIG_RUNTIME_NAMES = "MJR_CONFIG_RUNTIME_NAMES"
    MJR_CONFIG_RUNTIME_URIS = "MJR_CONFIG_RUNTIME_URIS"
    MJR_CONFIG_RUNTIME_SOURCES = "MJR_CONFIG_RUNTIME_SOURCES"

    MJR_USER_CONFIG_NAME = "MJR_USER_CONFIG_NAME"
    MJR_USER_CONFIG_URI = "MJR_USER_CONFIG_URI"
    MJR_USER_CONFIG_SOURCE = "MJR_USER_CONFIG_SOURCE"


class MOJO_CONFIG_VARIABLES:

    MJR_NAME = MOJO_CONFIG_OVERRIDES.MJR_NAME

    MJR_HOME_DIRECTORY = os.path.expanduser("~/{}".format(MJR_NAME))

    MJR_CONFIG_USE_CREDENTIALS = MOJO_CONFIG_OVERRIDES.MJR_CONFIG_USE_CREDENTIALS
    MJR_CONFIG_USE_LANDSCAPE = MOJO_CONFIG_OVERRIDES.MJR_CONFIG_USE_LANDSCAPE
    MJR_CONFIG_USE_RUNTIME = MOJO_CONFIG_OVERRIDES.MJR_CONFIG_USE_RUNTIME
    MJR_CONFIG_USE_TOPOLOGY = MOJO_CONFIG_OVERRIDES.MJR_CONFIG_USE_TOPOLOGY

    MJR_CONFIG_DIRECTORY = os.path.join(MJR_HOME_DIRECTORY, "config")

    MJR_CONFIG_PASS_PHRASE = None

    MJR_CONFIG_CREDENTIAL_NAMES = None
    MJR_CONFIG_CREDENTIAL_URIS = None
    MJR_CONFIG_CREDENTIAL_SOURCES = None

    MJR_CONFIG_LANDSCAPE_NAMES = None
    MJR_CONFIG_LANDSCAPE_URIS = None
    MJR_CONFIG_LANDSCAPE_SOURCES = None

    MJR_CONFIG_TOPOLOGY_NAMES = None
    MJR_CONFIG_TOPOLOGY_URIS = None
    MJR_CONFIG_TOPOLOGY_SOURCES = None

    MJR_CONFIG_RUNTIME_NAMES = None
    MJR_CONFIG_RUNTIME_URIS = None
    MJR_CONFIG_RUNTIME_SOURCES = None

    MJR_USER_CONFIG_NAME = "user-runtime"
    MJR_USER_CONFIG_SOURCE = MJR_CONFIG_DIRECTORY
    MJR_USER_CONFIG_URI = None

